[package]
name = "fast_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
libloading = "0.8.1"
nom = "7.1.3"
unwrap = "1.2.1"
vec1 = "1.10.1"
